spring.application.name=zeropapel
cors.allowed-origin=${CORS_ALLOWED_ORIGIN}

# Configuracoes do Banco de Dados
spring.datasource.url=${URL_BD}
spring.datasource.username=${USER_BD}
spring.datasource.password=${SENHA_BD}
spring.jpa.hibernate.ddl-auto=update

# Configuracoes do JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}